### ISSUE TITLE
dose not found index.html

### ISSUE THREAD

**Issue by mubinnngithub1999** [FlafyDev/epub_reader#13]
in pubspace.yaml file we have    `assets:  - assets/index.html `
 but doesn't exist in assets folder

**Comment by FlafyDev** [comment]
You have to build the index.html yourself. 

To get the index.html please refer to steps 2 and 3 of "Running from source" 

![IMG_20221122_003221.jpg](https://user-images.githubusercontent.com/44374434/203171445-e7ef867f-c11f-44c2-80ac-282028e54617.jpg)

**Comment by mubinnngithub1999** [comment]
![image](https://user-images.githubusercontent.com/99246323/204215211-dc65e755-baf2-4775-b793-275c4c2423f3.png)

**Comment by mubinnngithub1999** [comment]
i dont know why it is not wok
i write this command in epub-renderer but still not work

**Comment by mubinnngithub1999** [comment]
https://user-images.githubusercontent.com/99246323/204225995-ca747994-9a15-4f70-9e6b-fedf99f227b8.mp4

**Comment by mubinnngithub1999** [comment]
and i created index.html manually it was  worked until i tap Read and show nothing

**Comment by FlafyDev** [comment]
> ![image](https://user-images.githubusercontent.com/99246323/204215211-dc65e755-baf2-4775-b793-275c4c2423f3.png)
> 

You might need to run `yarn install`
