### ISSUE TITLE
When reading does not display the content of the book page

### ISSUE THREAD

**Issue by nduc86686** [FlafyDev/epub_reader#15]
When reading does not display the content of the book page

**Comment by nduc86686** [comment]
<img width="306" alt="Screen Shot 2023-05-11 at 09 59 53" src="https://github.com/FlafyDev/epub_reader/assets/89825540/b2eb5b91-c997-4b5b-bc73-0668a819f913">

**Comment by kat2512** [comment]
Fix được chưa bạn

**Comment by nduc86686** [comment]
Rồi nhé bạn

> Fix được chưa bạn

**Comment by gitNTT** [comment]
> 

Cho tôi xin code đã fix lỗi với
